# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "it-IT"
reviews:
  profile: "assertive"
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  # Abilita la generazione automatica di "finishing touches"
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true
  path_filters:
    - "!**/node_modules/**"
    - "!**/dist/**"
    - "!**/coverage/**"
    - "!**/__pycache__/**"
    - "!**/htmlcov/**"
    - "!**/playwright-report/**"
    - "!**/test-results/**"
    - "!**/temp/**"
    - "!conoscenza/**"
    - "!conoscenza_Bkup/**"
    - "!bmad-method/**"
    - "apps/api/**"
    - "apps/web/**"
    - "docs/**"
  tools:
    eslint:
      enabled: true
    ruff:
      enabled: true
    gitleaks:
      enabled: true
    markdownlint:
      enabled: true
knowledge_base:
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns:
      - "docs/architecture/**/*.md"
      - "docs/tech-reference/**/*.md"

# Istruzioni specifiche per la generazione di codice e test
code_generation:
  unit_tests:
    path_instructions:
      - path: "apps/api/**/*.py"
        instructions: |
          Usa pytest e pytest-asyncio.
          Mocka le chiamate esterne (OpenAI, Supabase, Database).
          Copri i casi limite e la gestione degli errori.
      - path: "apps/web/**/*.tsx"
        instructions: |
          Usa Vitest e React Testing Library.
          Testa il rendering dei componenti e le interazioni utente.
          Mocka gli hook personalizzati.

      # Removed filesMD because it is listed in .gitignore and not visible to CodeRabbit
chat:
  auto_reply: true
